services:
  db:
    image: postgres:18
    container_name: wo-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: workorders
    ports:
      - "5433:5432"
      # HOST:CONTAINER
    volumes:
      - pgdata:/var/lib/postgresql
      # old version, pgdata:/var/lib/postgresql/data, not compatible with v18
volumes:
  pgdata: